export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INIT = "SET_INIT";
export const FETCH_INGREDIENTS_FAILED = "FETCH_INGREDIENTS_FAILED";

export const PURCHASE_BURGER_START = "PURCHASE_BURGER_START";
export const BURGER_ORDER_SUCCESS = "BURGER_ORDER_SUCCESS";
export const BURGER_ORDER_FAILED = "BURGER_ORDER_FAILED";
export const PURCHASE_INIT = "PURCHASE_INIT";
